# Generated by Django 4.1.7 on 2023-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_Mark', models.DecimalField(auto_created=True, db_column='db_Mark', db_index=True, decimal_places=10, default=0, help_text='help: Mark is DB column', max_digits=20, max_length=40, verbose_name='v_Mark')),
                ('n_BDate', models.DateTimeField(auto_created=True, db_column='db_BDate', default='01-01-2000', help_text='help: BDate is DB column', max_length=32, verbose_name='v_BDate')),
                ('n_Name', models.CharField(auto_created=True, blank=True, db_column='db_Name', default='Unknown', help_text='help: Name is DB column', max_length=50, verbose_name='v_Name')),
            ],
        ),
    ]
