# Generated by Django 4.1.7 on 2023-03-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='n_BDate',
            field=models.DateTimeField(auto_created=True, db_column='db_BDate', help_text='help: BDate is DB column', max_length=32, verbose_name='v_BDate'),
        ),
    ]
